name: hide-comment
description: hide comment(s) in a pull request
inputs:
  authors:
    description: multi-line string of author condition
    required: false
  starts-with:
    description: multi-line string of starts-with condition
    required: false
  ends-with:
    description: multi-line string of ends-with condition
    required: false
  contains:
    description: multi-line string of contains condition
    required: false
  issue-number:
    description: Number of an issue or pull request on which to hide comment(s)
    required: false
  token:
    description: GitHub token to post a comment
    required: true
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'dist/index.js'
