name: hide-comment
description: Hide comment(s) of a pull request or issue

inputs:
  authors:
    description: Author condition (multi-line string)
    required: false
  starts-with:
    description: Starts-with condition (multi-line string)
    required: false
  ends-with:
    description: Ends-with condition (multi-line string)
    required: false
  contains:
    description: Contains condition (multi-line string)
    required: false
  issue-number:
    description: Number of an issue or pull request on which to hide comment(s)
    required: false
  token:
    description: GitHub token to post a comment
    required: true
    default: ${{ github.token }}

outputs:
  starts-with:
    description: Same as inputs.starts-with
  ends-with:
    description: Same as inputs.ends-with

runs:
  using: 'node20'
  main: 'dist/index.js'
