name: hide-comment
description: hide comment(s) in a pull request
inputs:
  authors:
    description: multi-line string of author filter
    required: false
    default: github-actions
  starts-with:
    description: multi-line string of starts-with filter
    required: false
  ends-with:
    description: multi-line string of ends-with filter
    required: false
  token:
    description: GitHub token to post a comment
    required: true
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
